#!/bin/sh

/bin/sleep 20

cd /opt/lockserver/

/opt/lockserver/init_button.sh

( while true
  do
    /opt/lockserver/lockd.py 2>> /var/log/lockserver.log >> /var/log/lockserver.debug.log
    sleep 5
  done
) &
