CREATE TABLE hashes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	hash VARCHAR(40),
	accesstype INTEGER,
	charges INTEGER,
	member VARCHAR(60),
	expires DATE,
	lastuse DATE
);

CREATE TABLE log (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	event INTEGER,
	eventtime DATETIME,
	hash INTEGER
);
